### ISSUE TITLE
Transaction error when creating multiple relationships between two entities

### ISSUE THREAD

**Issue by kalisitonga** [h-omer/neo4j-versioner-core#25]
**Describe the bug**
Great library, thank you for creating it! I created a copy of the `shouldCreateTheRelationshipAndTheNewCurrentStateBetweenEntities` test and added a loop to create 10 relationships between the two initialized entities. It fails on this line:

Line:
`Relationship relationship = session.run(String.format(query, entityA.id(), entityB.id(), testType)).single().get("relationship").asRelationship();`

Error:
`org.neo4j.driver.v1.exceptions.ClientException: The requested operation cannot be performed, because it has to be performed in a transaction. Ensure you are wrapping your operation in the appropriate transaction boilerplate and try again.`

Stack trace:
```
org.neo4j.driver.v1.exceptions.ClientException: The requested operation cannot be performed, because it has to be performed in a transaction. Ensure you are wrapping your operation in the appropriate transaction boilerplate and try again.
 at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:122)
 at org.neo4j.driver.internal.InternalStatementResult.blockingGet(InternalStatementResult.java:134)
 at org.neo4j.driver.internal.InternalStatementResult.single(InternalStatementResult.java:81)
 at org.homer.versioner.core.procedure.RelationshipProcedureTest.shouldCreateTheRelationshipAndTheNewCurrentStateBetweenEntitiesLoop(RelationshipProcedureTest.java:277)
 at org.neo4j.harness.junit.Neo4jRule$1.evaluate(Neo4jRule.java:79)
 Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause
 at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:67)
 at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:104)
 at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.unpackFailureMessage(MessageReaderV1.java:83)
 at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:59)
 at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83)
 at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35)
 at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
 at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1389)
 at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
 at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1203)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
 at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
 at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
 at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
 at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
 at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
 at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
 at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
 at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:750)
```

I am using the 2.0.3 version of the library with neo4j 3.5.x. Do you happen to know of a workaround or any guidance on resolving? I get the same error when writing a single cypher query that calls `graph.versioner.relationship.create(start, end, "relType")` for a list of start/end entities (versioned nodes). I also tried calling the  `RelationshipProcedureBuilder` directly in a custom procedure and then tried wrapping the single query and then the RelationshipProcedureBuilder call in a `try (Transaction tx = db.beginTx())` but get the same error at random points in the loop. Thank you!

**To Reproduce**
Created this test:

```
@Test
    public void shouldCreateTheRelationshipAndTheNewCurrentStateBetweenEntitiesLoop() throws Throwable {

        try (Driver driver = GraphDatabase
                .driver(neo4j.boltURI(), Config.build().withEncryption().toConfig());
                Session session = driver.session()) {

            // Given
            Node entityA = initEntity(session);
            Node entityB = initEntity(session);
            String testType = "testType";

            for (int i = 0; i < 10; i++) {

                // When
                String query = "MATCH (a:Entity), (b:Entity) WHERE id(a) = %d AND id(b) = %d WITH a, b CALL graph.versioner.relationship.create(a, b, '%s') YIELD relationship RETURN relationship";
                Relationship relationship = session.run(String.format(query, entityA.id(), entityB.id(), testType))
                        **.single()**
                        .get("relationship").asRelationship();

                // Then
                String querySourceCurrent = "MATCH (e:Entity)-[:CURRENT]-(s:State) WHERE id(e) = %d RETURN s";
                String queryDestinationR = "MATCH (e:Entity)<-[:FOR]-(r:R) WHERE id(e) = %d RETURN r";
                Node sourceCurrent = session.run(String.format(querySourceCurrent, entityA.id())).single().get("s")
                        .asNode();
                Node destinationR = session.run(String.format(queryDestinationR, entityB.id())).single().get("r")
                        .asNode();
                Relationship expected = new InternalRelationship(0L, sourceCurrent.id(), destinationR.id(), testType);

                assertThat(relationship).isEqualToIgnoringGivenFields(expected, "id");
            }
        }

    }

```
**Expected behavior**
Be able to call the procedure multiple times

**Comment by kalisitonga** [comment]
I found the issue, at least it fixed my scenario and seems to align with another method in the class.

src/main/java/org/homer/versioner/core/procedure/RelationshipProcedure.java

relationshipCreate method:

boolean exists = StreamSupport.stream(sourceCurrentState.get().getRelationships(Direction.OUTGOING, RelationshipType.withName(type)).spliterator(), **true**).anyMatch(relationship -> relationship.getEndNode().getId() == destinationRNode.get().getId());

Switching the parallel parameter to false fixes the error I reported and matches the relationshipsCreateFrom method in the class.

Thank you again for creating this great library!
